

#pragma once

#include "NativeGameplayTags.h"

namespace RaveGameplayTags
{
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Move);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Look);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interact);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Sprint);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Jump);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Climb);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Evade);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_PrimaryAttack);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_PrimaryAttackCharge);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_SecondaryAttack);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Identity);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Skill_1);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Skill_2);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Skill_3);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Skill_4);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Spell_1);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Spell_2);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Spell_3);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Spell_4);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Spell_5);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Module_1);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Module_2);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Module_3);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Module_4);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Module_5);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Module_6);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Property_Cancellable);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Property_BlockMove);

	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Interact);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Sprint);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Jump);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Evade);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_PrimaryAttack);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_SecondaryAttack);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Barrier);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Identity);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Skill_1);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Skill_2);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Skill_3);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Skill_4);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Spell_1);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Spell_2);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Spell_3);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Spell_4);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Spell_5);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Module_1);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Module_2);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Module_3);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Module_4);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Module_5);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Module_6);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Escape);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_CharacterSelect);

	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Collision_Begin);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Collision_End);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Combo_Begin);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Combo_End);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Block_Begin);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Block_End);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Sprint);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Launch);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Spawn);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Invoke);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Damage);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Land);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Knockdown);

	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEffect);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEffect_Damage);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEffect_Healing);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEffect_Cooldown);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEffect_Force);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEffect_Stun);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEffect_Property_RemoveByDamage);

	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_BlockMove);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_ZeroAcceleration);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Blocking);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Evade);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Debuff_Stun);

	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Healing);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Force);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Cooldown);
	RAVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Duration);
}